projectName: "myProject"
inDir: "proto"
outDir: "out"
forceGeneration: true
languages:
  Java:
    additionalParameters:
      enableMavenPublish: true
      groupId: "com.example"
      repositoryUrl: "https://repo.maven.my.org"
      repositoryUsername: "my_user"
      repositoryPassword: "{{ .Env.MAVEN_PASSWORD }}"
  PHP:
    additionalParameters:
      vendor: "my-company"
      phpVersion: "^8.3"
  TypeScript: