projectName: "myProject"
inDir: "proto"
outDir: "out"
languages:
  Java:
    enablePublish: true
    additionalParameters:
      groupId: "com.example"
      repositoryUrl: "https://repo.maven.my.org"
      repositoryUsername: "my_user"
      repositoryPassword: "{{ .Env.MAVEN_PASSWORD }}"
  PHP:
  TypeScript: